[colors.bright]
black = "0x707a8c"
blue = "0x73d0ff"
cyan = "0x95e6cb"
green = "0xbae67e"
magenta = "0xd4bfff"
red = "0xff3333"
white = "0xcbccc6"
yellow = "0xffa759"

[colors.cursor]
cursor = "0xffa759"
text = "0xcbccc6"

[colors.normal]
black = "0x1f2430"
blue = "0x73d0ff"
cyan = "0x95e6cb"
green = "0xbae67e"
magenta = "0xd4bfff"
red = "0xff3333"
white = "0xcbccc6"
yellow = "0xffa759"

[colors.primary]
background = "0x1f2430"
foreground = "0xcbccc6"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NL Nerd Font"
style = "bold"

[font.italic]
family = "JetBrainsMono NL Nerd Font"
style = "bold"

[font.normal]
family = "JetBrainsMono NL Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
