[colors.bright]
black = "0x504945"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a45"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.cursor]
cursor = "0xe78a45"
text = "0xd4be98"

[colors.normal]
black = "0x504945"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a45"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NL Nerd Font"
style = "bold"

[font.italic]
family = "JetBrainsMono NL Nerd Font"
style = "bold"

[font.normal]
family = "JetBrainsMono NL Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
title = "Alacritty"
# opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
